<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UsbDiskDoctor.Core\UsbDiskDoctor.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsbDiskDoctor.Diagnostics\UsbDiskDoctor.Diagnostics.csproj" />
  </ItemGroup>

</Project>
